// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'get_price_usecase_test.dart' as get_price_usecase_test;
import 'price_test.dart' as price_test;
import 'remote_datasource_test.dart' as remote_datasource_test;
import 'ticket_provider_test.dart' as ticket_provider_test;
import 'ticket_test.dart' as ticket_test;
import 'widget_test.dart' as widget_test;

void main() {
  ticket_test.main();
  price_test.main();
  ticket_provider_test.main();
  widget_test.main();
  remote_datasource_test.main();
  get_price_usecase_test.main();
}
